set_time: 1200

data: C1

fragments: 8

iter_num: 15 #决定外部挖掘次数iter-1
batch_size: 128
it_num: 5 #决定内部挖掘次数num-1
epochs: 5 #epoch*q为训练执行次数
q: 50

weight1: 5.0
weight2: 1
weight3: 1

epsilon: 1.0
epsilon_decay: 0.9
epsilon_min: 0.01

fedprox_mu: 0.01  # FedProx的mu值，推荐范围 0.001 到 0.1，可以从0.01开始尝试

gamma: 0.99
#high_quality_threshold: 1.0

learning_rate: 0.001
log_dir: runs/vision/测试周期内最后一轮启动LAHC3
#phi: 0.95
#process_timeout: 600
#barrier_timeout: 300
