# Example parameter combinations for experiments
# This file defines which parameters to vary across experiments

# Time limits to test
set_time: [60]  # 12min, 60min

#Datasets
data: [C1, C2, C3, C4, C5, C6, W1, W2, W3, W4, W5, W6] #C2, C3, C4, C5, C6, W1, W2, W3, W4, W5, W6
#数据分组 推荐2-12
fragments: [8]
# ALNS parameters
iter_num: [5]
it_num: [5]
epochs: [5]
q: [50]
batch_size: [128]

# DQN parameters
learning_rate: [0.001]

epsilon: [1.0]
epsilon_decay: [0.9]
epsilon_min: [0.01]

fedprox_mu: [0.01]

gamma: [0.99]



#phi: [0.95]
## Reward weights
#weight1: [ 1.0]  # Reward weight
#weight2: [ 0]  # Penalty quantity weight
#weight3: [ 0]  # Penalty time weight

